# -*- coding: utf-8 -*-
"""spam_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQ72bRvDc2hSqHY6ehVv9K51eY1k3hAJ

## **Import packages**
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

"""## **Import Dataset**"""

data=pd.read_csv("/content/drive/MyDrive/machine-learning-data/Youtube01-Psy.csv")
print(data.sample(5))

"""Split the column"""

data = data[["CONTENT", "CLASS"]]
print(data.sample(10))

"""## **Indicate 0 for not spam and 1 for spam**"""

data["CLASS"]= data["CLASS"].map({0:"Not SPAM", 1: "SPAM"})
print(data.sample(5))

"""## **Train Dataset with Bernoulli Algorithm**"""

x=np.array(data["CONTENT"])
y=np.array(data["CLASS"])

cv=CountVectorizer()
x=cv.fit_transform(x)
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=42)

model=BernoulliNB()
model.fit(xtrain, ytrain)

print(model.score(xtest, ytest))

"""## **Validate Trained Data**"""

hWorld="please like http://www.grandi.com"
data=cv.transform([hWorld]).toarray()
print(model.predict(data))